/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 18 18:06:59 GMT 2025
 */

package org.apache.bookkeeper.client;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class BookKeeperAdmin_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) System.getProperties().clone();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.bookkeeper.client.BookKeeperAdmin"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = SandboxMode.RECOMMENDED;
    Sandbox.initializeSecurityManagerForSUT();
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    System.setProperties((java.util.Properties) defaultProperties.clone());
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    Sandbox.goingToExecuteSUTCode();
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    Sandbox.doneWithExecutingSUTCode();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    System.setProperties((java.util.Properties) defaultProperties.clone());
    System.setProperty("file.encoding", "UTF-8");
    System.setProperty("java.awt.headless", "true");
    System.setProperty("java.io.tmpdir", "/tmp");
    System.setProperty("user.country", "GB");
    System.setProperty("user.dir", "/home/zyler/IdeaProjects/bookkeeper/bookkeeper-server");
    System.setProperty("user.home", "/home/zyler");
    System.setProperty("user.language", "en");
    System.setProperty("user.name", "zyler");
    System.setProperty("user.timezone", "Europe/Rome");
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(BookKeeperAdmin_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.bookkeeper.discover.BookieServiceInfo",
      "org.apache.bookkeeper.stats.Gauge",
      "com.google.common.collect.Lists$RandomAccessPartition",
      "org.apache.bookkeeper.meta.MetadataDrivers",
      "org.apache.bookkeeper.discover.RegistrationClient$RegistrationListener",
      "org.apache.commons.lang.exception.NestableException",
      "org.apache.commons.configuration.AbstractConfiguration",
      "org.apache.bookkeeper.proto.BookkeeperInternalCallbacks$WriteCallback",
      "org.apache.bookkeeper.zookeeper.ZooKeeperClient",
      "org.apache.bookkeeper.client.EnsemblePlacementPolicy",
      "com.google.common.collect.Sets$2",
      "com.google.common.collect.Sets$3",
      "org.apache.bookkeeper.client.api.CreateBuilder",
      "com.google.common.collect.Sets$1",
      "org.apache.bookkeeper.common.conf.ConfigKeyGroup",
      "org.apache.bookkeeper.client.api.LedgersIterator",
      "org.apache.bookkeeper.common.util.JsonUtil$ParseJsonException",
      "org.apache.bookkeeper.meta.LedgerUnderreplicationManager",
      "org.apache.commons.lang.text.StrSubstitutor",
      "org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage",
      "org.apache.bookkeeper.meta.UnderreplicatedLedger",
      "org.apache.bookkeeper.util.LedgerIdFormatter",
      "org.apache.commons.configuration.Configuration",
      "org.apache.bookkeeper.common.conf.Validator",
      "org.apache.bookkeeper.meta.MetadataClientDriver",
      "org.apache.commons.lang.exception.NestableRuntimeException",
      "org.apache.bookkeeper.common.conf.validators.ClassValidator",
      "org.apache.bookkeeper.client.AsyncCallback$CreateCallback",
      "org.apache.bookkeeper.discover.RegistrationClient",
      "org.apache.bookkeeper.client.BookKeeper$Builder",
      "com.google.common.collect.Lists$Partition",
      "org.apache.bookkeeper.replication.ReplicationException",
      "com.google.common.collect.Lists",
      "org.apache.bookkeeper.client.BookKeeper$2",
      "com.google.common.collect.Sets$4",
      "org.apache.bookkeeper.bookie.SkipListFlusher",
      "org.apache.zookeeper.Watcher",
      "org.apache.commons.configuration.event.EventSource",
      "org.apache.commons.configuration.interpol.ConfigurationInterpolator",
      "org.apache.bookkeeper.client.BookieWatcher",
      "org.apache.bookkeeper.meta.LedgerAuditorManager",
      "org.apache.bookkeeper.conf.ClientConfiguration",
      "org.apache.bookkeeper.feature.Feature",
      "com.google.common.base.Preconditions",
      "org.apache.bookkeeper.meta.zk.ZKMetadataClientDriver",
      "org.apache.bookkeeper.client.BookieInfoReader$BookieInfo",
      "org.apache.bookkeeper.util.StringEntryFormatter",
      "io.netty.buffer.ByteBufAllocator",
      "org.apache.bookkeeper.common.conf.ConfigKey",
      "com.google.common.collect.ImmutableCollection",
      "org.apache.bookkeeper.client.BookKeeperAdmin$LedgerEntriesIterable",
      "org.apache.zookeeper.KeeperException$NoNodeException",
      "org.apache.bookkeeper.proto.BookkeeperInternalCallbacks$LedgerMetadataListener",
      "org.apache.bookkeeper.discover.RegistrationManager",
      "org.apache.bookkeeper.replication.ReplicationException$BKAuditException",
      "org.apache.bookkeeper.client.AsyncCallback$ReadCallback",
      "org.apache.bookkeeper.meta.zk.ZKMetadataBookieDriver",
      "org.apache.bookkeeper.client.api.BookKeeper",
      "org.apache.bookkeeper.proto.BookkeeperInternalCallbacks$Processor",
      "org.apache.bookkeeper.common.allocator.PoolingPolicy",
      "org.apache.bookkeeper.client.LedgerHandle",
      "com.google.common.collect.ImmutableSet",
      "org.apache.bookkeeper.common.util.OrderedScheduler",
      "com.google.common.collect.Lists$AbstractListWrapper",
      "org.apache.commons.configuration.AbstractConfiguration$1",
      "org.apache.bookkeeper.client.api.WriteHandle",
      "org.apache.bookkeeper.meta.LedgerIdGenerator",
      "org.apache.bookkeeper.client.api.ForceableHandle",
      "org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException",
      "com.google.common.collect.Lists$StringAsImmutableList",
      "org.apache.bookkeeper.proto.BookieClient",
      "com.google.common.collect.Lists$2",
      "org.apache.bookkeeper.client.api.LedgerMetadata",
      "org.apache.bookkeeper.client.BookKeeperClientStats",
      "com.google.common.collect.Lists$1",
      "org.apache.bookkeeper.common.conf.ConfigKeyGroup$ConfigKeyGroupBuilder",
      "org.apache.bookkeeper.stats.OpStatsData",
      "org.apache.bookkeeper.stats.NullStatsLogger$NullOpStatsLogger",
      "org.apache.bookkeeper.client.BookieInfoReader$BookieInfoMap",
      "org.apache.commons.lang.text.StrLookup",
      "com.google.common.collect.ImmutableList",
      "com.google.common.util.concurrent.UncheckedExecutionException",
      "org.apache.bookkeeper.client.WeightedRandomSelection$WeightedObject",
      "org.apache.bookkeeper.client.LedgerEntry",
      "io.netty.channel.EventLoopGroup",
      "org.apache.zookeeper.KeeperException",
      "org.apache.bookkeeper.stats.NullStatsLogger$NullCounter",
      "org.apache.bookkeeper.conf.ServerConfiguration",
      "org.apache.zookeeper.AsyncCallback$StringCallback",
      "org.apache.bookkeeper.client.api.ReadHandle",
      "org.apache.commons.lang.exception.Nestable",
      "org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase",
      "org.apache.bookkeeper.client.LedgerOpenOp",
      "org.apache.bookkeeper.client.api.OpenBuilder",
      "org.apache.bookkeeper.util.EntryFormatter",
      "org.apache.bookkeeper.common.util.JsonUtil",
      "org.apache.commons.configuration.CompositeConfiguration",
      "org.apache.bookkeeper.client.api.ListLedgersResultBuilder",
      "org.apache.bookkeeper.client.EnsemblePlacementPolicy$PlacementPolicyAdherence",
      "org.apache.bookkeeper.stats.OpStatsLogger",
      "org.apache.bookkeeper.bookie.LedgerStorage",
      "org.apache.bookkeeper.client.BKException$MetaStoreException",
      "org.apache.bookkeeper.zookeeper.RetryPolicy",
      "com.google.common.collect.Lists$TransformingRandomAccessList",
      "org.apache.bookkeeper.proto.BookkeeperInternalCallbacks$GenericCallback",
      "org.apache.zookeeper.ZooKeeper",
      "org.apache.bookkeeper.client.ClientInternalConf",
      "org.apache.bookkeeper.client.api.BookKeeperBuilder",
      "org.apache.bookkeeper.client.BookKeeper",
      "org.apache.bookkeeper.client.AsyncCallback$RecoverCallback",
      "org.apache.bookkeeper.bookie.CompactableLedgerStorage",
      "org.apache.bookkeeper.common.allocator.OutOfMemoryPolicy",
      "org.apache.bookkeeper.bookie.SortedLedgerStorage",
      "org.apache.bookkeeper.stats.StatsLogger",
      "org.apache.bookkeeper.client.BookKeeper$DigestType",
      "org.apache.commons.configuration.ConfigurationException",
      "org.apache.bookkeeper.net.BookieId",
      "org.apache.bookkeeper.meta.MetadataBookieDriver",
      "org.apache.bookkeeper.meta.MetadataDrivers$MetadataBookieDriverInfo",
      "org.apache.bookkeeper.meta.exceptions.MetadataException",
      "org.apache.bookkeeper.bookie.InterleavedLedgerStorage",
      "org.apache.bookkeeper.common.allocator.LeakDetectionPolicy",
      "com.google.common.collect.Sets$SetView",
      "org.apache.bookkeeper.feature.FeatureProvider",
      "org.apache.bookkeeper.proto.BookieAddressResolver",
      "org.apache.bookkeeper.replication.ReplicationException$CompatibilityException",
      "org.apache.bookkeeper.client.LedgerFragmentReplicator",
      "com.google.common.collect.Lists$TransformingSequentialList",
      "org.apache.bookkeeper.client.AsyncCallback$DeleteCallback",
      "com.google.common.primitives.IntsMethodsForWeb",
      "org.apache.bookkeeper.meta.LedgerManager",
      "org.apache.bookkeeper.common.util.ReflectionUtils",
      "org.apache.bookkeeper.client.BookieInfoReader$InstanceState",
      "org.apache.bookkeeper.util.LedgerIdFormatter$LongLedgerIdFormatter",
      "org.apache.bookkeeper.net.DNSToSwitchMapping",
      "org.apache.bookkeeper.client.AsyncCallback$IsClosedCallback",
      "org.apache.bookkeeper.client.LedgerFragment",
      "org.apache.zookeeper.AsyncCallback",
      "org.apache.zookeeper.AsyncCallback$StatCallback",
      "org.apache.bookkeeper.client.api.ListLedgersResult",
      "org.apache.bookkeeper.stats.StatsProvider",
      "org.apache.bookkeeper.client.ReadOnlyLedgerHandle",
      "com.google.common.collect.ImmutableEnumSet",
      "com.google.common.collect.Lists$RandomAccessListWrapper",
      "org.apache.bookkeeper.client.api.BKException",
      "org.apache.bookkeeper.client.AsyncCallback$ReadLastConfirmedCallback",
      "org.apache.bookkeeper.client.api.OpBuilder",
      "org.apache.commons.configuration.event.ConfigurationListener",
      "org.apache.bookkeeper.bookie.BookieException",
      "org.apache.bookkeeper.client.AsyncCallback$OpenCallback",
      "org.apache.bookkeeper.common.conf.Type",
      "org.apache.bookkeeper.bookie.DefaultEntryLogger$EntryLogListener",
      "com.google.common.base.Converter",
      "org.apache.bookkeeper.client.api.Handle",
      "org.apache.bookkeeper.stats.NullStatsLogger",
      "com.google.common.base.Function",
      "org.apache.bookkeeper.conf.AbstractConfiguration",
      "org.apache.bookkeeper.bookie.CacheCallback",
      "com.google.common.collect.CollectPreconditions",
      "org.apache.bookkeeper.client.BKException",
      "com.google.common.collect.Sets",
      "com.google.common.primitives.Ints$IntConverter",
      "org.apache.bookkeeper.conf.UncheckedConfigurationException",
      "org.apache.commons.configuration.event.ConfigurationErrorListener",
      "io.netty.util.HashedWheelTimer",
      "org.apache.bookkeeper.client.BookKeeperAdmin",
      "io.netty.util.Timer",
      "org.apache.bookkeeper.replication.ReplicationException$UnavailableException",
      "org.apache.bookkeeper.client.BookieInfoReader$State",
      "org.apache.bookkeeper.client.BookieWatcherImpl",
      "org.apache.bookkeeper.feature.CacheableFeatureProvider",
      "org.apache.bookkeeper.client.SyncCallbackUtils$SyncOpenCallback",
      "org.apache.bookkeeper.feature.SettableFeatureProvider",
      "org.apache.commons.configuration.event.ConfigurationEvent",
      "org.apache.bookkeeper.client.BookKeeper$ListLedgersResultImpl",
      "org.apache.bookkeeper.client.ClientContext",
      "org.apache.bookkeeper.client.BookieInfoReader",
      "org.apache.bookkeeper.client.BookKeeperAdmin$7",
      "org.apache.commons.configuration.ConversionException",
      "org.apache.bookkeeper.client.BookKeeper$SyncLedgerIterator",
      "org.apache.bookkeeper.versioning.Versioned",
      "org.apache.bookkeeper.meta.MetadataDrivers$MetadataClientDriverInfo",
      "org.apache.bookkeeper.common.conf.ConfigKey$ConfigKeyBuilder",
      "org.apache.zookeeper.AsyncCallback$VoidCallback",
      "org.apache.bookkeeper.bookie.BookieException$CookieNotFoundException",
      "org.apache.bookkeeper.client.AsyncCallback",
      "org.apache.bookkeeper.meta.LayoutManager",
      "org.apache.bookkeeper.stats.Counter",
      "io.netty.util.concurrent.EventExecutorGroup",
      "org.apache.bookkeeper.client.DistributionSchedule",
      "org.apache.commons.configuration.event.ConfigurationErrorEvent",
      "org.apache.bookkeeper.common.util.OrderedExecutor",
      "com.google.common.primitives.Ints",
      "org.apache.zookeeper.KeeperException$NodeExistsException",
      "org.apache.commons.configuration.ConfigurationRuntimeException",
      "org.apache.bookkeeper.meta.LedgerManagerFactory",
      "org.apache.bookkeeper.client.AsyncCallback$ReadLastConfirmedAndEntryCallback",
      "org.apache.bookkeeper.common.conf.ConfigException",
      "org.apache.bookkeeper.common.conf.validators.RangeValidator",
      "org.apache.bookkeeper.client.api.DeleteBuilder",
      "org.apache.bookkeeper.client.BKException$BKLedgerRecoveryException"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.apache.bookkeeper.client.BookKeeper", false, BookKeeperAdmin_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.bookkeeper.conf.ClientConfiguration", false, BookKeeperAdmin_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.bookkeeper.conf.ServerConfiguration", false, BookKeeperAdmin_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.bookkeeper.discover.RegistrationClient$RegistrationListener", false, BookKeeperAdmin_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.bookkeeper.stats.StatsLogger", false, BookKeeperAdmin_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(BookKeeperAdmin_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.bookkeeper.client.BookKeeperAdmin",
      "org.apache.bookkeeper.client.BookKeeperAdmin$LedgerEntriesIterable",
      "org.apache.bookkeeper.client.BookKeeperAdmin$SyncObject",
      "org.apache.bookkeeper.client.BookKeeperAdmin$1",
      "org.apache.bookkeeper.client.BookKeeperAdmin$2",
      "org.apache.bookkeeper.client.BookKeeperAdmin$3",
      "org.apache.bookkeeper.client.BookKeeperAdmin$4",
      "org.apache.bookkeeper.client.BookKeeperAdmin$5",
      "org.apache.bookkeeper.client.BookKeeperAdmin$1RecoverCallbackWrapper",
      "org.apache.bookkeeper.client.BookKeeperAdmin$6",
      "org.apache.bookkeeper.client.BookKeeperAdmin$ResultCallBack",
      "org.apache.bookkeeper.client.BookKeeperAdmin$7",
      "org.apache.bookkeeper.client.BookKeeperAdmin$8",
      "org.apache.bookkeeper.stats.NullStatsLogger$NullOpStatsLogger",
      "org.apache.bookkeeper.stats.OpStatsData",
      "org.apache.bookkeeper.stats.NullStatsLogger$NullCounter",
      "org.apache.bookkeeper.stats.NullStatsLogger",
      "org.apache.bookkeeper.common.concurrent.FutureUtils",
      "org.apache.bookkeeper.client.EnsemblePlacementPolicy$PlacementPolicyAdherence",
      "org.apache.bookkeeper.client.LedgerFragment$ReplicateType",
      "org.apache.commons.lang3.ArrayUtils",
      "org.apache.bookkeeper.common.util.ReflectionUtils",
      "com.google.common.collect.Sets",
      "org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase",
      "org.apache.bookkeeper.meta.MetadataDrivers$MetadataClientDriverInfo",
      "org.apache.bookkeeper.meta.zk.ZKMetadataClientDriver",
      "org.apache.bookkeeper.meta.MetadataDrivers$MetadataBookieDriverInfo",
      "org.apache.bookkeeper.meta.zk.ZKMetadataBookieDriver",
      "org.apache.bookkeeper.meta.MetadataDrivers",
      "org.apache.bookkeeper.meta.exceptions.Code",
      "org.apache.bookkeeper.net.DNS",
      "org.apache.bookkeeper.client.BookKeeper",
      "org.apache.commons.configuration.event.EventSource",
      "org.apache.commons.configuration.AbstractConfiguration",
      "org.apache.commons.configuration.CompositeConfiguration",
      "org.apache.bookkeeper.conf.AbstractConfiguration",
      "org.apache.bookkeeper.common.conf.ConfigKeyGroup$ConfigKeyGroupBuilder",
      "org.apache.bookkeeper.common.conf.ConfigKeyGroup",
      "org.apache.bookkeeper.common.conf.ConfigKey",
      "org.apache.bookkeeper.common.conf.ConfigKey$ConfigKeyBuilder",
      "org.apache.bookkeeper.common.conf.Type",
      "com.google.common.collect.Lists",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.CollectPreconditions",
      "com.google.common.primitives.IntsMethodsForWeb",
      "com.google.common.primitives.Ints",
      "org.apache.bookkeeper.common.conf.validators.ClassValidator",
      "org.apache.bookkeeper.common.conf.validators.RangeValidator",
      "org.apache.bookkeeper.conf.ServerConfiguration",
      "org.apache.bookkeeper.conf.ClientConfiguration",
      "org.apache.bookkeeper.client.LedgerFragmentReplicator",
      "org.apache.bookkeeper.client.SyncCallbackUtils$SyncOpenCallback",
      "org.apache.bookkeeper.client.LedgerOpenOp",
      "org.apache.bookkeeper.client.BookKeeper$2",
      "org.apache.bookkeeper.feature.CacheableFeatureProvider",
      "org.apache.bookkeeper.feature.SettableFeatureProvider",
      "org.apache.bookkeeper.client.ClientInternalConf",
      "org.apache.commons.logging.impl.NoOpLog",
      "org.apache.commons.configuration.BaseConfiguration",
      "org.apache.commons.configuration.PropertyConverter",
      "org.apache.commons.lang.BooleanUtils",
      "org.apache.commons.lang.text.StrMatcher$CharMatcher",
      "org.apache.commons.lang.text.StrMatcher$CharSetMatcher",
      "org.apache.commons.lang.text.StrMatcher$TrimMatcher",
      "org.apache.commons.lang.text.StrMatcher$NoMatcher",
      "org.apache.commons.lang.text.StrMatcher",
      "org.apache.commons.lang.text.StrMatcher$StringMatcher",
      "org.apache.commons.lang.text.StrSubstitutor",
      "org.apache.commons.lang.text.StrLookup$MapStrLookup",
      "org.apache.commons.lang.text.StrLookup",
      "org.apache.commons.configuration.interpol.ConstantLookup",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "org.apache.commons.configuration.interpol.EnvironmentLookup",
      "org.apache.commons.configuration.MapConfiguration",
      "org.apache.commons.configuration.EnvironmentConfiguration",
      "org.apache.commons.configuration.interpol.ConfigurationInterpolator",
      "org.apache.commons.configuration.AbstractConfiguration$1",
      "org.apache.commons.lang.text.StrBuilder",
      "org.apache.commons.lang.StringUtils",
      "org.apache.bookkeeper.feature.FixedValueFeature",
      "org.apache.bookkeeper.feature.SettableFeature",
      "org.apache.bookkeeper.client.DefaultSpeculativeRequestExecutionPolicy",
      "org.apache.bookkeeper.common.util.OrderedExecutor",
      "org.apache.bookkeeper.common.util.OrderedScheduler",
      "org.apache.bookkeeper.common.util.OrderedExecutor$AbstractBuilder",
      "org.apache.bookkeeper.common.util.OrderedScheduler$SchedulerBuilder",
      "io.netty.util.concurrent.DefaultThreadFactory",
      "io.netty.util.internal.ObjectUtil",
      "com.google.common.util.concurrent.ThreadFactoryBuilder",
      "com.google.common.util.concurrent.ThreadFactoryBuilder$1",
      "com.google.common.collect.ForwardingObject",
      "com.google.common.util.concurrent.ForwardingExecutorService",
      "com.google.common.util.concurrent.ForwardingListeningExecutorService",
      "org.apache.bookkeeper.common.util.BoundedScheduledExecutorService",
      "org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService",
      "com.google.common.util.concurrent.MoreExecutors",
      "com.google.common.util.concurrent.AbstractListeningExecutorService",
      "com.google.common.util.concurrent.MoreExecutors$ListeningDecorator",
      "com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator",
      "com.google.common.util.concurrent.internal.InternalFutureFailureAccess",
      "com.google.common.util.concurrent.AbstractFuture$AtomicHelper",
      "com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper$1",
      "com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper",
      "com.google.common.util.concurrent.AbstractFuture",
      "com.google.common.util.concurrent.GwtFluentFutureCatchingSpecialization",
      "com.google.common.util.concurrent.FluentFuture",
      "com.google.common.util.concurrent.FluentFuture$TrustedFuture",
      "com.google.common.util.concurrent.TrustedListenableFutureTask",
      "com.google.common.util.concurrent.InterruptibleTask$DoNothingRunnable",
      "com.google.common.util.concurrent.InterruptibleTask",
      "com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask",
      "org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable",
      "io.netty.util.concurrent.FastThreadLocalRunnable",
      "io.netty.util.internal.logging.InternalLoggerFactory",
      "io.netty.util.internal.logging.Slf4JLoggerFactory",
      "io.netty.util.internal.logging.Slf4JLoggerFactory$NopInstanceHolder",
      "io.netty.util.internal.logging.AbstractInternalLogger",
      "io.netty.util.internal.logging.LocationAwareSlf4JLogger",
      "io.netty.util.concurrent.FastThreadLocalThread",
      "com.google.common.util.concurrent.AbstractFuture$Waiter"
    );
  }
}
