/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 18 18:06:59 GMT 2025
 */

package org.apache.bookkeeper.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.bookkeeper.client.BookKeeper;
import org.apache.bookkeeper.client.BookKeeperAdmin;
import org.apache.bookkeeper.client.ClientContext;
import org.apache.bookkeeper.client.LedgerEntry;
import org.apache.bookkeeper.conf.ClientConfiguration;
import org.apache.bookkeeper.conf.ServerConfiguration;
import org.apache.bookkeeper.discover.RegistrationClient;
import org.apache.bookkeeper.meta.MetadataClientDriver;
import org.apache.bookkeeper.stats.Counter;
import org.apache.bookkeeper.stats.OpStatsLogger;
import org.apache.bookkeeper.stats.StatsLogger;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BookKeeperAdmin_ESTest extends BookKeeperAdmin_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BookKeeper bookKeeper0 = mock(BookKeeper.class, new ViolatedAssumptionAnswer());
      ClientConfiguration clientConfiguration0 = mock(ClientConfiguration.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(clientConfiguration0).getReplicationRateByBytes();
      BookKeeperAdmin bookKeeperAdmin0 = new BookKeeperAdmin(bookKeeper0, clientConfiguration0);
      // Undeclared exception!
      try { 
        bookKeeperAdmin0.triggerAudit();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.BookKeeperAdmin", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = mock(ServerConfiguration.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(serverConfiguration0).getMetadataServiceUriUnchecked();
      doReturn((String) null).when(serverConfiguration0).getZkLedgersRootPath();
      try { 
        BookKeeperAdmin.nukeExistingCluster(serverConfiguration0, "Error on closing ledger handle for {}.", "desiredNumZonesPerWriteQuorum", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StatsLogger statsLogger0 = mock(StatsLogger.class, new ViolatedAssumptionAnswer());
      doReturn((Counter) null, (Counter) null).when(statsLogger0).getCounter(anyString());
      doReturn((OpStatsLogger) null, (OpStatsLogger) null, (OpStatsLogger) null, (OpStatsLogger) null).when(statsLogger0).getOpStatsLogger(anyString());
      ClientConfiguration clientConfiguration0 = mock(ClientConfiguration.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(clientConfiguration0).getReplicationRateByBytes();
      BookKeeperAdmin bookKeeperAdmin0 = null;
      try {
        bookKeeperAdmin0 = new BookKeeperAdmin((BookKeeper) null, statsLogger0, clientConfiguration0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.BookKeeperAdmin", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BookKeeper bookKeeper0 = mock(BookKeeper.class, new ViolatedAssumptionAnswer());
      BookKeeperAdmin bookKeeperAdmin0 = null;
      try {
        bookKeeperAdmin0 = new BookKeeperAdmin(bookKeeper0, (ClientConfiguration) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Client configuration cannot be null
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BookKeeperAdmin bookKeeperAdmin0 = null;
      try {
        bookKeeperAdmin0 = new BookKeeperAdmin((ClientConfiguration) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.ClientInternalConf", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BookKeeper bookKeeper0 = mock(BookKeeper.class, new ViolatedAssumptionAnswer());
      ClientConfiguration clientConfiguration0 = mock(ClientConfiguration.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(clientConfiguration0).getReplicationRateByBytes();
      BookKeeperAdmin bookKeeperAdmin0 = new BookKeeperAdmin(bookKeeper0, clientConfiguration0);
      // Undeclared exception!
      try { 
        bookKeeperAdmin0.getCurrentAuditor();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.BookKeeperAdmin", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BookKeeper bookKeeper0 = mock(BookKeeper.class, new ViolatedAssumptionAnswer());
      doReturn((MetadataClientDriver) null).when(bookKeeper0).getMetadataClientDriver();
      BookKeeperAdmin bookKeeperAdmin0 = new BookKeeperAdmin(bookKeeper0);
      RegistrationClient.RegistrationListener registrationClient_RegistrationListener0 = mock(RegistrationClient.RegistrationListener.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        bookKeeperAdmin0.watchWritableBookiesChanged(registrationClient_RegistrationListener0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.BookKeeperAdmin", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BookKeeper bookKeeper0 = mock(BookKeeper.class, new ViolatedAssumptionAnswer());
      StatsLogger statsLogger0 = mock(StatsLogger.class, new ViolatedAssumptionAnswer());
      doReturn((Counter) null, (Counter) null).when(statsLogger0).getCounter(anyString());
      doReturn((OpStatsLogger) null, (OpStatsLogger) null, (OpStatsLogger) null, (OpStatsLogger) null).when(statsLogger0).getOpStatsLogger(anyString());
      ClientConfiguration clientConfiguration0 = mock(ClientConfiguration.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(clientConfiguration0).getReplicationRateByBytes();
      BookKeeperAdmin bookKeeperAdmin0 = new BookKeeperAdmin(bookKeeper0, statsLogger0, clientConfiguration0);
      // Undeclared exception!
      try { 
        bookKeeperAdmin0.setLostBookieRecoveryDelay(2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.BookKeeperAdmin", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        BookKeeperAdmin.newBookKeeperAdmin((ClientConfiguration) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.ClientInternalConf", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BookKeeper bookKeeper0 = mock(BookKeeper.class, new ViolatedAssumptionAnswer());
      BookKeeperAdmin bookKeeperAdmin0 = new BookKeeperAdmin(bookKeeper0);
      // Undeclared exception!
      try { 
        bookKeeperAdmin0.getAvailableBookies();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.BookKeeperAdmin", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BookKeeper bookKeeper0 = mock(BookKeeper.class, new ViolatedAssumptionAnswer());
      doReturn((ClientContext) null).when(bookKeeper0).getClientCtx();
      StatsLogger statsLogger0 = mock(StatsLogger.class, new ViolatedAssumptionAnswer());
      doReturn((Counter) null, (Counter) null).when(statsLogger0).getCounter(anyString());
      doReturn((OpStatsLogger) null, (OpStatsLogger) null, (OpStatsLogger) null, (OpStatsLogger) null).when(statsLogger0).getOpStatsLogger(anyString());
      ClientConfiguration clientConfiguration0 = mock(ClientConfiguration.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(clientConfiguration0).getReplicationRateByBytes();
      BookKeeperAdmin bookKeeperAdmin0 = new BookKeeperAdmin(bookKeeper0, statsLogger0, clientConfiguration0);
      // Undeclared exception!
      try { 
        bookKeeperAdmin0.openLedger((-1003L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.BookKeeperAdmin", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = mock(ServerConfiguration.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(serverConfiguration0).getMetadataServiceUri();
      try { 
        BookKeeperAdmin.initNewCluster(serverConfiguration0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.net.URI$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      try { 
        BookKeeperAdmin.format((ServerConfiguration) null, true, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.meta.MetadataDrivers", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BookKeeper bookKeeper0 = mock(BookKeeper.class, new ViolatedAssumptionAnswer());
      ClientConfiguration clientConfiguration0 = mock(ClientConfiguration.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(clientConfiguration0).getReplicationRateByBytes();
      BookKeeperAdmin bookKeeperAdmin0 = new BookKeeperAdmin(bookKeeper0, clientConfiguration0);
      Iterable<LedgerEntry> iterable0 = bookKeeperAdmin0.readEntries(0L, 600000L, 4);
      assertNotNull(iterable0);
  }
}
