/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 18 18:04:59 GMT 2025
 */

package org.apache.bookkeeper.client;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class LedgerHandle_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) System.getProperties().clone();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.bookkeeper.client.LedgerHandle"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = SandboxMode.RECOMMENDED;
    Sandbox.initializeSecurityManagerForSUT();
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    System.setProperties((java.util.Properties) defaultProperties.clone());
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    Sandbox.goingToExecuteSUTCode();
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    Sandbox.doneWithExecutingSUTCode();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    System.setProperties((java.util.Properties) defaultProperties.clone());
    System.setProperty("file.encoding", "UTF-8");
    System.setProperty("java.awt.headless", "true");
    System.setProperty("java.io.tmpdir", "/tmp");
    System.setProperty("user.country", "GB");
    System.setProperty("user.dir", "/home/zyler/IdeaProjects/bookkeeper/bookkeeper-server");
    System.setProperty("user.home", "/home/zyler");
    System.setProperty("user.language", "en");
    System.setProperty("user.name", "zyler");
    System.setProperty("user.timezone", "Europe/Rome");
    System.setProperty("sun.arch.data.model", "64");
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(LedgerHandle_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.bookkeeper.client.AsyncCallback$CloseCallback",
      "org.apache.bookkeeper.client.BKException$BKInterruptedException",
      "org.apache.bookkeeper.client.api.ListLedgersResult",
      "com.google.protobuf.ProtocolMessageEnum",
      "org.apache.bookkeeper.client.ReadLastConfirmedAndEntryOp$LastConfirmedAndEntryCallback",
      "org.apache.bookkeeper.stats.Gauge",
      "org.apache.bookkeeper.client.ExplicitLacFlushPolicy",
      "org.apache.bookkeeper.client.BKException$BKMetadataVersionException",
      "org.apache.bookkeeper.client.AsyncCallback$ReadCallback",
      "org.apache.bookkeeper.client.api.BKException",
      "org.apache.bookkeeper.client.AsyncCallback$ReadLastConfirmedCallback",
      "org.apache.bookkeeper.client.BKException$BKNoSuchEntryException",
      "org.apache.bookkeeper.client.LedgerHandle$LastConfirmedCtx",
      "org.apache.bookkeeper.client.api.BookKeeper",
      "org.apache.bookkeeper.client.api.BKException$LogMessagePool",
      "org.apache.bookkeeper.client.BKException$BKReadException",
      "org.apache.bookkeeper.client.LedgerHandle",
      "org.apache.bookkeeper.client.api.Handle",
      "org.apache.bookkeeper.client.api.LedgersIterator",
      "org.apache.bookkeeper.client.PendingReadLacOp$LacCallback",
      "org.apache.bookkeeper.client.api.WriteHandle",
      "org.apache.bookkeeper.client.BookKeeper",
      "org.apache.bookkeeper.client.api.ForceableHandle",
      "org.apache.bookkeeper.client.BKException",
      "org.apache.bookkeeper.versioning.Version$Occurred",
      "org.apache.bookkeeper.client.SyncCallbackUtils$SyncAddCallback",
      "com.google.common.cache.CacheLoader",
      "com.google.protobuf.Internal$EnumLite",
      "org.apache.bookkeeper.client.BookKeeper$DigestType",
      "org.apache.bookkeeper.client.api.LedgerMetadata",
      "org.apache.bookkeeper.client.BKException$BKIncorrectParameterException",
      "org.apache.bookkeeper.versioning.Version",
      "org.apache.bookkeeper.versioning.LongVersion",
      "org.apache.bookkeeper.client.SyncCallbackUtils$FutureReadLastConfirmedAndEntry",
      "org.apache.bookkeeper.client.BookKeeper$ListLedgersResultImpl",
      "org.apache.bookkeeper.client.ClientContext",
      "org.apache.bookkeeper.client.api.BKException$Code",
      "org.apache.bookkeeper.client.ReadLastConfirmedOp$LastConfirmedDataCallback",
      "org.apache.bookkeeper.client.SyncCallbackUtils$FutureReadLastConfirmed",
      "org.apache.bookkeeper.client.LedgerHandle$HandleState",
      "org.apache.bookkeeper.client.BookKeeper$SyncLedgerIterator",
      "org.apache.bookkeeper.client.BookiesHealthInfo",
      "org.apache.bookkeeper.client.LedgerHandle$NoopCloseCallback",
      "org.apache.bookkeeper.client.AsyncCallback$AddCallbackWithLatency",
      "org.apache.bookkeeper.versioning.Versioned",
      "org.apache.bookkeeper.client.api.DigestType",
      "org.apache.bookkeeper.client.AsyncCallback$AddCallback",
      "org.apache.bookkeeper.client.LedgerHandle$1",
      "org.apache.bookkeeper.proto.DataFormats$LedgerMetadataFormat$DigestType",
      "org.apache.bookkeeper.client.DistributionSchedule",
      "org.apache.bookkeeper.client.api.ReadHandle",
      "org.apache.bookkeeper.client.AsyncCallback$ReadLastConfirmedAndEntryCallback",
      "org.apache.bookkeeper.client.api.WriteFlag"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(LedgerHandle_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.bookkeeper.client.LedgerHandle",
      "com.google.common.cache.CacheLoader",
      "org.apache.bookkeeper.client.LedgerHandle$1",
      "org.apache.bookkeeper.client.LedgerHandle$2",
      "org.apache.bookkeeper.client.LedgerHandle$3",
      "org.apache.bookkeeper.client.LedgerHandle$6",
      "org.apache.bookkeeper.client.LedgerHandle$4",
      "org.apache.bookkeeper.client.LedgerHandle$7",
      "org.apache.bookkeeper.client.LedgerHandle$5",
      "org.apache.bookkeeper.client.LedgerHandle$10",
      "org.apache.bookkeeper.client.LedgerHandle$8",
      "org.apache.bookkeeper.client.LedgerHandle$9",
      "org.apache.bookkeeper.client.LedgerHandle$11",
      "org.apache.bookkeeper.client.LedgerHandle$15",
      "org.apache.bookkeeper.client.LedgerHandle$12",
      "org.apache.bookkeeper.client.LedgerHandle$13",
      "org.apache.bookkeeper.client.LedgerHandle$14",
      "org.apache.bookkeeper.client.LedgerHandle$LastConfirmedCtx",
      "org.apache.bookkeeper.client.LedgerHandle$HandleState",
      "org.apache.bookkeeper.client.BookKeeper$DigestType",
      "org.apache.bookkeeper.client.api.DigestType",
      "org.apache.bookkeeper.client.BookKeeper$3",
      "org.apache.bookkeeper.proto.DataFormats$LedgerMetadataFormat$DigestType$1",
      "org.apache.bookkeeper.proto.DataFormats$LedgerMetadataFormat$DigestType",
      "org.apache.bookkeeper.proto.checksum.DigestManager$2",
      "io.netty.util.concurrent.FastThreadLocal",
      "org.apache.bookkeeper.proto.checksum.DigestManager$1",
      "io.netty.util.internal.UnpaddedInternalThreadLocalMap",
      "io.netty.util.internal.logging.InternalLoggerFactory",
      "io.netty.util.internal.logging.Slf4JLoggerFactory",
      "io.netty.util.internal.logging.Slf4JLoggerFactory$NopInstanceHolder",
      "io.netty.util.internal.logging.AbstractInternalLogger",
      "io.netty.util.internal.logging.LocationAwareSlf4JLogger",
      "io.netty.util.internal.ObjectUtil",
      "io.netty.util.internal.SystemPropertyUtil",
      "io.netty.util.internal.SystemPropertyUtil$1",
      "io.netty.util.internal.InternalThreadLocalMap",
      "org.apache.bookkeeper.proto.checksum.DigestManager",
      "org.apache.bookkeeper.proto.checksum.MacDigestManager",
      "org.apache.bookkeeper.client.ExplicitLacFlushPolicy$1",
      "org.apache.bookkeeper.client.ExplicitLacFlushPolicy",
      "io.netty.util.internal.logging.Log4J2LoggerFactory",
      "io.netty.util.internal.logging.Log4JLoggerFactory",
      "io.netty.util.internal.logging.JdkLoggerFactory",
      "io.netty.util.internal.PlatformDependent0$1",
      "io.netty.util.internal.ReflectionUtil",
      "io.netty.util.internal.PlatformDependent0$2",
      "io.netty.util.internal.PlatformDependent0$3",
      "io.netty.util.internal.PlatformDependent0$4",
      "io.netty.util.internal.PlatformDependent0$5",
      "io.netty.util.internal.PlatformDependent0$6",
      "io.netty.util.internal.PlatformDependent0$12",
      "io.netty.util.internal.PlatformDependent0",
      "io.netty.util.internal.PlatformDependent$1",
      "io.netty.util.internal.PlatformDependent$2",
      "io.netty.util.internal.CleanerJava6$1",
      "io.netty.util.internal.CleanerJava6",
      "io.netty.util.internal.PlatformDependent$4",
      "io.netty.util.internal.PlatformDependent",
      "io.netty.util.internal.CleanerJava9$1",
      "io.netty.util.internal.CleanerJava9",
      "io.netty.util.ResourceLeakDetector$Level",
      "io.netty.util.internal.EmptyArrays",
      "io.netty.util.ResourceLeakDetector",
      "io.netty.buffer.AbstractByteBufAllocator",
      "io.netty.buffer.ByteBuf",
      "io.netty.buffer.EmptyByteBuf",
      "io.netty.util.internal.StringUtil",
      "io.netty.buffer.UnpooledByteBufAllocator$UnpooledByteBufAllocatorMetric",
      "io.netty.util.internal.LongAdderCounter",
      "io.netty.buffer.UnpooledByteBufAllocator",
      "io.netty.buffer.Unpooled",
      "io.netty.util.Recycler$EnhancedHandle",
      "io.netty.util.Recycler$1",
      "io.netty.util.Recycler",
      "org.apache.bookkeeper.client.PendingAddOp$1",
      "io.netty.util.Recycler$2",
      "org.apache.bookkeeper.client.PendingAddOp",
      "org.apache.bookkeeper.client.api.LedgerMetadata$State",
      "org.apache.bookkeeper.client.LedgerHandle$NoopCloseCallback",
      "org.apache.bookkeeper.client.api.WriteFlag",
      "org.apache.bookkeeper.client.EnsembleUtils",
      "com.google.common.collect.ImmutableMap",
      "com.google.common.collect.RegularImmutableMap",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.RegularImmutableList",
      "org.apache.bookkeeper.client.api.BKException$LogMessagePool",
      "org.apache.bookkeeper.client.api.BKException",
      "org.apache.bookkeeper.versioning.LongVersion",
      "org.apache.bookkeeper.versioning.Versioned",
      "org.apache.bookkeeper.client.LedgerRecoveryOp",
      "org.apache.bookkeeper.client.ExplicitLacFlushPolicy$ExplicitLacFlushPolicyImpl",
      "org.apache.bookkeeper.client.ExplicitLacFlushPolicy$ExplicitLacFlushPolicyImpl$1",
      "io.netty.util.NettyRuntime$AvailableProcessorsHolder",
      "io.netty.util.NettyRuntime",
      "io.netty.buffer.PooledByteBufAllocator$1",
      "io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache",
      "io.netty.buffer.SizeClasses",
      "io.netty.buffer.PoolThreadCache",
      "io.netty.buffer.PoolArena",
      "io.netty.buffer.PoolArena$DirectArena",
      "io.netty.buffer.PoolSubpage",
      "io.netty.buffer.PoolChunkList",
      "io.netty.buffer.PooledByteBufAllocatorMetric",
      "io.netty.buffer.PooledByteBufAllocator",
      "io.netty.util.ResourceLeakDetectorFactory$DefaultResourceLeakDetectorFactory",
      "io.netty.util.ResourceLeakDetectorFactory",
      "io.netty.buffer.AbstractByteBuf",
      "io.netty.util.internal.ReferenceCountUpdater",
      "io.netty.buffer.AbstractReferenceCountedByteBuf$1",
      "io.netty.buffer.AbstractReferenceCountedByteBuf",
      "io.netty.buffer.UnpooledHeapByteBuf",
      "io.netty.buffer.UnpooledUnsafeHeapByteBuf",
      "org.apache.bookkeeper.net.BookieId",
      "io.netty.handler.codec.UnsupportedValueConverter",
      "io.netty.handler.codec.DefaultHeaders",
      "io.netty.util.internal.MathUtil",
      "io.netty.handler.codec.DefaultHeaders$HeaderEntry",
      "io.netty.buffer.UnpooledDirectByteBuf",
      "io.netty.util.internal.shaded.org.jctools.util.Pow2",
      "io.netty.handler.codec.EmptyHeaders",
      "io.netty.handler.codec.http2.EmptyHttp2Headers",
      "io.netty.util.AsciiString$1",
      "io.netty.util.AsciiString$2",
      "io.netty.util.AsciiString",
      "io.netty.buffer.AdaptiveByteBufAllocator",
      "io.netty.buffer.AdaptivePoolingAllocator$MagazineCaching",
      "io.netty.buffer.AdaptivePoolingAllocator",
      "io.netty.buffer.AdaptiveByteBufAllocator$DirectChunkAllocator",
      "io.netty.util.internal.shaded.org.jctools.queues.ConcurrentCircularArrayQueueL0Pad",
      "io.netty.util.internal.shaded.org.jctools.queues.ConcurrentCircularArrayQueue",
      "io.netty.util.internal.shaded.org.jctools.queues.ConcurrentSequencedCircularArrayQueue",
      "io.netty.util.internal.shaded.org.jctools.queues.MpmcArrayQueueL1Pad",
      "io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess",
      "io.netty.util.internal.shaded.org.jctools.queues.MpmcArrayQueueProducerIndexField",
      "io.netty.util.internal.shaded.org.jctools.queues.MpmcArrayQueueL2Pad",
      "io.netty.util.internal.shaded.org.jctools.queues.MpmcArrayQueueConsumerIndexField",
      "io.netty.util.internal.shaded.org.jctools.queues.MpmcArrayQueueL3Pad",
      "io.netty.util.internal.shaded.org.jctools.queues.MpmcArrayQueue",
      "io.netty.util.internal.shaded.org.jctools.util.RangeUtil",
      "io.netty.buffer.UnpooledUnsafeDirectByteBuf",
      "org.apache.bookkeeper.client.impl.LedgerEntryImpl$1",
      "org.apache.bookkeeper.client.impl.LedgerEntryImpl",
      "io.netty.util.Recycler$LocalPool",
      "io.netty.util.internal.PlatformDependent$Mpsc$1",
      "io.netty.util.internal.PlatformDependent$Mpsc",
      "io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueuePad1",
      "io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueueProducerFields",
      "io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueuePad2",
      "io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueueConsumerFields",
      "io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueuePad3",
      "io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueueColdProducerFields",
      "io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue",
      "io.netty.util.internal.shaded.org.jctools.queues.MpscChunkedArrayQueueColdProducerFields",
      "io.netty.util.internal.shaded.org.jctools.queues.MpscChunkedArrayQueue",
      "io.netty.util.internal.shaded.org.jctools.util.UnsafeRefArrayAccess",
      "io.netty.util.internal.shaded.org.jctools.queues.MessagePassingQueueUtil",
      "io.netty.util.internal.shaded.org.jctools.queues.LinkedArrayQueueUtil",
      "io.netty.util.Recycler$DefaultHandle",
      "org.apache.bookkeeper.client.SyncCallbackUtils$SyncAddCallback",
      "org.apache.commons.configuration.event.EventSource",
      "org.apache.commons.configuration.AbstractConfiguration",
      "org.apache.commons.configuration.CompositeConfiguration",
      "org.apache.bookkeeper.conf.AbstractConfiguration",
      "org.apache.bookkeeper.common.conf.ConfigKeyGroup$ConfigKeyGroupBuilder",
      "org.apache.bookkeeper.common.conf.ConfigKeyGroup",
      "org.apache.bookkeeper.common.conf.ConfigKey",
      "org.apache.bookkeeper.common.conf.ConfigKey$ConfigKeyBuilder",
      "org.apache.bookkeeper.common.conf.Type",
      "com.google.common.collect.Lists",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.CollectPreconditions",
      "com.google.common.primitives.IntsMethodsForWeb",
      "com.google.common.primitives.Ints",
      "org.apache.bookkeeper.common.conf.validators.ClassValidator",
      "org.apache.bookkeeper.common.conf.validators.RangeValidator",
      "org.apache.bookkeeper.conf.ServerConfiguration",
      "org.apache.commons.logging.impl.NoOpLog",
      "org.apache.commons.configuration.BaseConfiguration",
      "org.apache.commons.configuration.PropertyConverter",
      "io.netty.buffer.CompositeByteBuf$1",
      "io.netty.buffer.CompositeByteBuf$2",
      "io.netty.buffer.CompositeByteBuf",
      "io.netty.util.internal.ThreadExecutorMap",
      "io.netty.buffer.AbstractByteBufAllocator$1",
      "io.netty.buffer.CompositeByteBuf$Component",
      "io.netty.buffer.UnsafeByteBufUtil",
      "org.apache.bookkeeper.client.SyncCallbackUtils$SyncReadLastConfirmedCallback",
      "org.apache.commons.configuration.HierarchicalConfiguration",
      "org.apache.commons.configuration.AbstractHierarchicalFileConfiguration",
      "org.apache.commons.configuration.XMLConfiguration",
      "org.apache.commons.configuration.beanutils.DefaultBeanFactory",
      "org.apache.commons.configuration.DefaultConfigurationBuilder$ConfigurationProvider",
      "org.apache.commons.configuration.DefaultConfigurationBuilder$FileConfigurationProvider",
      "org.apache.commons.configuration.DefaultConfigurationBuilder$FileExtensionConfigurationProvider",
      "org.apache.commons.configuration.DefaultConfigurationBuilder$XMLConfigurationProvider",
      "org.apache.commons.configuration.DefaultConfigurationBuilder$ConfigurationBuilderProvider",
      "org.apache.commons.configuration.DefaultConfigurationBuilder",
      "org.apache.commons.configuration.tree.DefaultConfigurationNode",
      "org.apache.commons.configuration.HierarchicalConfiguration$Node",
      "org.apache.commons.configuration.tree.DefaultConfigurationNode$SubNodes",
      "org.apache.commons.configuration.AbstractFileConfiguration",
      "org.apache.commons.configuration.AbstractHierarchicalFileConfiguration$FileConfigurationDelegate",
      "org.apache.commons.configuration.XMLConfiguration$XMLFileConfigurationDelegate",
      "org.apache.commons.configuration.Lock",
      "org.apache.commons.configuration.DefaultFileSystem",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "org.apache.commons.configuration.FileSystem",
      "org.apache.commons.configuration.reloading.InvariantReloadingStrategy",
      "org.apache.commons.configuration.AbstractConfiguration$2",
      "org.apache.commons.configuration.resolver.DefaultEntityResolver",
      "org.apache.commons.lang.text.StrLookup$MapStrLookup",
      "org.apache.commons.lang.text.StrLookup",
      "org.apache.commons.configuration.DefaultConfigurationBuilder$1",
      "org.apache.commons.configuration.beanutils.BeanHelper",
      "org.apache.commons.configuration.DefaultConfigurationBuilder$ConfigurationBeanFactory",
      "org.apache.commons.configuration.DataConfiguration",
      "org.apache.commons.configuration.tree.DefaultExpressionEngine",
      "org.apache.commons.configuration.tree.DefaultConfigurationKey",
      "org.apache.commons.configuration.tree.DefaultConfigurationKey$KeyIterator",
      "org.apache.commons.configuration.MapConfiguration",
      "org.apache.commons.configuration.EnvironmentConfiguration",
      "io.netty.buffer.ByteBufUtil$1",
      "io.netty.util.CharsetUtil",
      "io.netty.buffer.ByteBufUtil$2",
      "io.netty.buffer.ByteBufUtil",
      "io.netty.buffer.ByteBufAllocator",
      "io.netty.handler.codec.DefaultHeaders$NameValidator$1",
      "io.netty.handler.codec.DefaultHeaders$NameValidator",
      "io.netty.handler.codec.DefaultHeaders$ValueValidator$1",
      "io.netty.handler.codec.DefaultHeaders$ValueValidator",
      "org.apache.bookkeeper.client.SyncCallbackUtils$FutureReadLastConfirmed",
      "com.google.common.base.Converter",
      "com.google.common.base.Converter$FunctionBasedConverter",
      "com.google.common.base.Converter$IdentityConverter",
      "com.google.common.base.Converter$ConverterComposition"
    );
  }
}
