/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 18 18:04:59 GMT 2025
 */

package org.apache.bookkeeper.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.EnumSet;
import java.util.StringTokenizer;
import org.apache.bookkeeper.client.BookKeeper;
import org.apache.bookkeeper.client.ClientContext;
import org.apache.bookkeeper.client.LedgerHandle;
import org.apache.bookkeeper.client.api.LedgerMetadata;
import org.apache.bookkeeper.client.api.WriteFlag;
import org.apache.bookkeeper.versioning.LongVersion;
import org.apache.bookkeeper.versioning.Versioned;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LedgerHandle_ESTest extends LedgerHandle_ESTest_scaffolding {

  //@Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LedgerHandle.NoopCloseCallback ledgerHandle_NoopCloseCallback0 = LedgerHandle.NoopCloseCallback.instance;
      StringTokenizer stringTokenizer0 = new StringTokenizer("", "handlers");
      // Undeclared exception!
      try { 
        ledgerHandle_NoopCloseCallback0.closeComplete(2434, (LedgerHandle) null, stringTokenizer0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.apache.bookkeeper.client.api.BKException
         //
         verifyException("org.apache.bookkeeper.client.LedgerHandle$NoopCloseCallback", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      ledgerHandle_LastConfirmedCtx0.setLastConfirmed(463L);
      boolean boolean0 = ledgerHandle_LastConfirmedCtx0.ready();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LongVersion longVersion0 = new LongVersion(0L);
      Versioned<LedgerMetadata> versioned0 = new Versioned<LedgerMetadata>((LedgerMetadata) null, longVersion0);
      BookKeeper.DigestType bookKeeper_DigestType0 = BookKeeper.DigestType.CRC32;
      EnumSet<WriteFlag> enumSet0 = WriteFlag.getWriteFlags(0);
      LedgerHandle ledgerHandle0 = null;
      try {
        ledgerHandle0 = new LedgerHandle((ClientContext) null, (-3350L), versioned0, bookKeeper_DigestType0, (byte[]) null, enumSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.LedgerHandle", e);
      }
  }

  //@Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LedgerHandle.NoopCloseCallback ledgerHandle_NoopCloseCallback0 = LedgerHandle.NoopCloseCallback.instance;
      // Undeclared exception!
      try { 
        ledgerHandle_NoopCloseCallback0.closeComplete((-11), (LedgerHandle) null, (Object) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.apache.bookkeeper.client.api.BKException
         //
         verifyException("org.apache.bookkeeper.client.LedgerHandle$NoopCloseCallback", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LedgerHandle.NoopCloseCallback ledgerHandle_NoopCloseCallback0 = LedgerHandle.NoopCloseCallback.instance;
      ledgerHandle_NoopCloseCallback0.closeComplete(0, (LedgerHandle) null, (Object) null);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      ledgerHandle_LastConfirmedCtx0.response = (-99L);
      boolean boolean0 = ledgerHandle_LastConfirmedCtx0.ready();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      boolean boolean0 = ledgerHandle_LastConfirmedCtx0.ready();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      long long0 = ledgerHandle_LastConfirmedCtx0.getlastConfirmed();
      assertEquals((-10L), long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      int int0 = ledgerHandle_LastConfirmedCtx0.getRC();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      ledgerHandle_LastConfirmedCtx0.setRC((-999));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LedgerHandle.NoopCloseCallback ledgerHandle_NoopCloseCallback0 = new LedgerHandle.NoopCloseCallback();
  }
}
