/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 06 22:43:17 GMT 2025
 */

package org.apache.bookkeeper.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.EnumSet;
import java.util.StringTokenizer;
import org.apache.bookkeeper.client.BookKeeper;
import org.apache.bookkeeper.client.ClientContext;
import org.apache.bookkeeper.client.LedgerHandle;
import org.apache.bookkeeper.client.api.LedgerMetadata;
import org.apache.bookkeeper.client.api.WriteFlag;
import org.apache.bookkeeper.versioning.LongVersion;
import org.apache.bookkeeper.versioning.Versioned;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LedgerHandle_ESTest extends LedgerHandle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LongVersion longVersion0 = new LongVersion(0L);
      assertNotNull(longVersion0);
      assertEquals(0L, longVersion0.getLongVersion());
      assertEquals("0", longVersion0.toString());
      
      Versioned<LedgerMetadata> versioned0 = new Versioned<LedgerMetadata>((LedgerMetadata) null, longVersion0);
      assertNotNull(versioned0);
      assertEquals(0L, longVersion0.getLongVersion());
      assertEquals("0", longVersion0.toString());
      
      BookKeeper.DigestType bookKeeper_DigestType0 = BookKeeper.DigestType.CRC32;
      EnumSet<WriteFlag> enumSet0 = WriteFlag.getWriteFlags(0);
      assertNotNull(enumSet0);
      assertEquals(0, enumSet0.size());
      
      LedgerHandle ledgerHandle0 = null;
      try {
        ledgerHandle0 = new LedgerHandle((ClientContext) null, (-3350L), versioned0, bookKeeper_DigestType0, (byte[]) null, enumSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.LedgerHandle", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LedgerHandle.NoopCloseCallback ledgerHandle_NoopCloseCallback0 = LedgerHandle.NoopCloseCallback.instance;
      assertNotNull(ledgerHandle_NoopCloseCallback0);
      
      StringTokenizer stringTokenizer0 = new StringTokenizer("", "handlers");
      assertNotNull(stringTokenizer0);
      assertEquals(0, stringTokenizer0.countTokens());
      
      // Undeclared exception!
      try {
        ledgerHandle_NoopCloseCallback0.closeComplete(2434, (LedgerHandle) null, stringTokenizer0);
        fail("Expecting exception: NoClassDefFoundError");

      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.apache.bookkeeper.client.api.BKException
         //
         verifyException("org.apache.bookkeeper.client.LedgerHandle$NoopCloseCallback", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      assertNotNull(ledgerHandle_LastConfirmedCtx0);
      
      ledgerHandle_LastConfirmedCtx0.response = (-2882382797L);
      boolean boolean0 = ledgerHandle_LastConfirmedCtx0.ready();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      assertNotNull(ledgerHandle_LastConfirmedCtx0);
      
      boolean boolean0 = ledgerHandle_LastConfirmedCtx0.ready();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      assertNotNull(ledgerHandle_LastConfirmedCtx0);
      
      long long0 = ledgerHandle_LastConfirmedCtx0.getlastConfirmed();
      assertEquals((-10L), long0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      assertNotNull(ledgerHandle_LastConfirmedCtx0);
      
      int int0 = ledgerHandle_LastConfirmedCtx0.getRC();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      assertNotNull(ledgerHandle_LastConfirmedCtx0);
      
      ledgerHandle_LastConfirmedCtx0.setLastConfirmed(3708L);
      boolean boolean0 = ledgerHandle_LastConfirmedCtx0.ready();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LedgerHandle.LastConfirmedCtx ledgerHandle_LastConfirmedCtx0 = new LedgerHandle.LastConfirmedCtx();
      assertNotNull(ledgerHandle_LastConfirmedCtx0);
      
      ledgerHandle_LastConfirmedCtx0.setRC((-1286));
  }
}
